### ISSUE TITLE
Submit button dithered after making changes

### ISSUE THREAD

**Issue by jwor80** [Ombi-app/Ombi#4567] opened 2022-03-28 15:27 UTC
**Describe the bug**
After making changes such as selecting load libraries for my Emby server the submit button does not un-dither to save the change.

**To Reproduce**
1. Go to Settings > Media Server > Emby > Load Libraries
2. Click on the libraries that you want o monitor
3. The submit button is dithered and there is no way to save the changes.

**Expected behavior**
I would expect to the submit button become available to save the changes

**Screenshots**
![Capture](https://user-images.githubusercontent.com/38135239/160432581-84323f1b-57f8-4187-8224-1b67b7a22cd9.JPG)

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Windows 64 bit

**Ombi Version (please complete the following information):**
 - Version 4.15.3
- Media Server Emby
- Database Type: MySQL

**Additional context**
This issue occurred in previous versions

**Comment by jwor80** [comment] 2022-04-30 14:55
Is there a work around I can use prior to this bug being fixed?  I have some Emby folder locations that I do not want to go out in the newsletters but I can't seem to find a way to disable them.  I've tried removing my Emby connection and re-adding with a custom folder list, but it's still sending out info for all the folders.

**Comment by tidusjar** [comment] 2022-04-30 20:06
The work around would be to make a change e.g. to the host name. Change the values and then save. Then put your host name back and save

**Comment by jwor80** [comment] 2022-04-30 20:34
Even if I change the host name the submit button is still dithered.  If I click away come back to the settings the host name defaults back to the original.  I tried verifying the server as well and the change is not saved.

**Comment by tidusjar** [comment] 2022-04-30 20:47
Ah hostname may not work in that case. Try another field. You need to depress the discover button. I’ll improve this but currently on vacation

**Comment by sephrat** [comment] 2023-05-18 05:57
Duplicate of https://github.com/Ombi-app/Ombi/issues/4424

**Closed by sephrat** 2023-05-18 05:57 UTC
Labels: bug / issue
