### ISSUE TITLE
APT repo not updated

### ISSUE THREAD

**Issue by jayfromm** [Ombi-app/Ombi#4560] opened 2022-03-26 14:07 UTC
**Describe the bug**
The APT repo at https://apt.ombi.app/develop or https://apt.ombi.app/master offers 4.7.11 as the latest. The app displays 'New Update Available' with 4.15.3 as the latest version.

As the method indicated for installation in the docs at https://docs.ombi.app/guides/installation/#debian-apt-repo, it is what I used. Is the APT repo still the best method?

**To Reproduce**
apt update on a Ubuntu/Debian system with the repo described in the docs (deb https://apt.ombi.app/develop jessie main) enabled. 4.7.11 is the latest version.

**Expected behavior**
 I should be seeing 4.15.3 available for update.

**Screenshots**
![Screenshot at 2022-03-26 06-47-01](https://user-images.githubusercontent.com/76223969/160242977-e29ec34c-abe2-4739-9b5b-91ecb5c8a1ca.png)
![Screenshot at 2022-03-26 06-47-14](https://user-images.githubusercontent.com/76223969/160242978-efeb7667-a044-4778-b207-d4a0ac4eba64.png)
![Screenshot at 2022-03-26 06-57-41](https://user-images.githubusercontent.com/76223969/160242981-5dd55895-7b85-4fc1-8554-24b4383f5c47.png)

**Logs (Logs directory where Ombi is located)**

**Desktop (please complete the following information):**

OS:  Mate on Debian 11

**Ombi Version (please complete the following information):**

Version: 4.7.11
Media Server: Plex
Database Type: MySQL

**Additional context**

**Comment by ristein** [comment] 2022-03-26 22:16
I have a similar issue:
I recently installed stable version via apt and got v4.10.2
Now I am trying to update but cant find a way.
After doing: echo "deb https://apt.ombi.app/develop jessie main" | sudo tee /etc/apt/sources.list.d/ombi.list
apt still says "ombi is already the newest version (4.10.2)." when trying to install, and with --reinstall it says "Reinstallation of ombi is not possible, it cannot be downloaded."
I also tried following the guides under updating in docs but ombi wouldnt start afterwards with following error:
sudo service ombi status
● ombi.service - Ombi - PMS Requests System
     Loaded: loaded (/lib/systemd/system/ombi.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: core-dump) since Sat 2022-03-26 23:01:54 CET; 943ms ago
    Process: 307836 ExecStart=/opt/Ombi/Ombi --storage /etc/Ombi/ (code=dumped, signal=ABRT)
   Main PID: 307836 (code=dumped, signal=ABRT)

**Comment by sephrat** [comment] 2022-03-27 07:15
Duplicate of https://github.com/Ombi-app/Ombi/issues/4505

**Closed** 2022-04-06 20:45 UTC
