### ISSUE TITLE
The cloudpackage of Ombi appears to be out of date.

### ISSUE THREAD

**Issue by BastionNtB** [Ombi-app/Ombi#4514] opened 2022-02-22 18:44 UTC
**Describe the bug**
The cloudpackage of Ombi appears to be out of date.

**To Reproduce**
Following the steps to install the v4 cloud package version found here: https://docs.ombi.app/guides/installation/#linux-systems
The repository does not seem to have the updated versions pushed to it. Current version it deploys is 4.3.3

**Expected behavior**
I would expect the repository to be updated, so that when apt update is run, the new version is deployed after running apt upgrade.

**Desktop (please complete the following information):**
 - OS: Ubuntu Server 20.04

**Ombi Version (please complete the following information):**
- Version 4.3.3
- Database Type: SQLite

**Comment by tidusjar** [comment] 2022-02-23 09:00
Duplicate of #4505

**Closed by tidusjar** 2022-02-23 09:00 UTC
