### ISSUE TITLE
Username not visible when i make request for them

### ISSUE THREAD

**Issue by CyanurePV** [Ombi-app/Ombi#4670] opened 2022-06-07 23:43 UTC
**Describe the bug**
The users without e-mail don't show correctly in requests

**To Reproduce**
1. Go to 'Découvrir'
2. Click on ' any show and ask about it, when you are an admin, the user list appear, but every user without email is filled blank'
3. See error

**Expected behavior**
The username must be visible

**Screenshots**

![Sans titre](https://user-images.githubusercontent.com/64288236/172501255-29061af1-367a-4a35-a9ea-8ab04426bc29.png)

**Logs (Logs directory where Ombi is located)**
--

**Desktop :**
 - OS: W10 Pro X64 [FR language]

**Ombi Version :**
 - Version 4.16.12
- Media Server  Plex
- Database Type: SQLite

**Additional context**

**Comment by Firetop** [comment] 2022-06-11 11:45
Duplicate of: https://github.com/Ombi-app/Ombi/issues/4664

**Comment by tidusjar** [comment] 2022-07-22 12:27
This has been fixed in develop

**Closed by tidusjar** 2022-07-22 12:27 UTC
