### ISSUE TITLE
Radarr frequent failed reuqests

### ISSUE THREAD

**Issue by hightechstl** [Ombi-app/Ombi#4564] opened 2022-03-28 01:10 UTC
**Describe the bug**
Randomly when requesting a movie it fails to send to Randarr and never processes.

**To Reproduce**
1. Go to Ombi
2. Request a movie
3. Look at log

**Expected behavior**
Movie requests are sent to Radarr for processing

**Screenshots**

**Logs (Logs directory where Ombi is located)**
![image](https://user-images.githubusercontent.com/13816103/160310108-1f67082a-7b90-4892-8661-5af8be279bed.png)

**Desktop (please complete the following information):**
 - OS: 20.04.1-Ubuntu

**Ombi Version (please complete the following information):**
 - Version 4.15.3
- Media Server Plex
- Database Type: SQLite (Please change if using MySQL)

**Additional context**
TV requests to Sonarr is working perfectly fine and some movie requests do make it through, but the majority fail and I have to manually add them to Radarr. Once they are finished in Radarr, Ombi DOES detect that they are finished and flag them as available.

Radarr version: 3.2.2.5080

**Comment by tidusjar** [comment] 2022-03-28 06:03
Are there any logs in radarr when this happens? It looks like radarr is closing the connection

**Comment by hightechstl** [comment] 2022-03-30 02:53
[https://pastebin.com/SRKbbEPM](url)

That is the log from Radarr, looks like you are right. I'm seeing a Message too long error. Not really sure what that means or how to fix that. Or maybe that's not even the relevant information. You're much wiser than I am...

**Comment by sephrat** [comment] 2022-03-30 06:43
I'm not sure about the root cause of those `System.Net.Sockets.SocketException: Message too long` errors, but have you consider upgrading Radarr? v4 has been stable for a couple of months now.

**Comment by hightechstl** [comment] 2022-03-31 02:22
> I'm not sure about the root cause of those `System.Net.Sockets.SocketException: Message too long` errors, but have you considered upgrading Radarr? v4 has been stable for a couple of months now.

I have tried a few times but keep having issues with upgrading to v4. Currently i'm running sonarr/radarr/sabnzbd/plex all on TrueNAS in a jail (not using the plugin, but manually installed in the jail)

**Comment by tidusjar** [comment] 2022-04-07 18:01
It's difficult to support many versions of 3rd party software. I'd recommend upgrading to radarr v4

**Closed by tidusjar** 2022-04-07 18:01 UTC
