### ISSUE TITLE
Partially Available prevents further TV requests?

### ISSUE THREAD

**Issue by bagobones** [Ombi-app/Ombi#4768] opened 2022-10-05 02:01 UTC
**Describe the bug**
If  a single episode of a TV show exists the request button is no longer available to users

**Expected behavior**
Should be able to request seasons  / episodes as long as the full season or episode does not already exist.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows and iOS browser

**Ombi Version (please complete the following information):**
 - Version 4.22.5
- Media Server Plex
- Database Type: MySQL

**Comment by sephrat** [comment] 2022-10-05 06:50
I can't reproduce. I have a TV show with only season 1 available, and I'm able to request other seasons.
The button should be hidden if all episodes are available or requested.

Can you please include screenshots of the whole TV show details page?

**Comment by bagobones** [comment] 2022-10-05 16:31
1. One episode exists in plex.
2. Navigate to show via discover
3. No request button, and no active requests in the requests section at the bottom.

In my case this will happen if I have only the pilot for the show for any new show.. Not sure when this started but we know it didn't always do this.

I think what is happening here is that the partial fill logic is not checking if there are ANY requests before removing the request button.

![Todd](https://user-images.githubusercontent.com/1587701/194112410-be15c160-03d7-4fe8-81e2-5986e3e5eafa.png)

**Comment by sephrat** [comment] 2022-10-05 16:49
Ah, I see it. Ombi considers it as "fully available" because the other episodes have not aired yet.
For some reason it seems to works fine if there is a request for it. 

I'm not sure why Ombi should say the TV show is fully available if there's an unaired episode, so I'll leave it up to @tidusjar 
https://github.com/Ombi-app/Ombi/blob/v4.27.6/src/Ombi.Core/Rule/Rules/Search/AvailabilityRuleHelper.cs#L43

**Comment by sephrat** [comment] 2023-05-17 17:26
Fixed in v4.29.0

**Closed by sephrat** 2023-05-17 17:26 UTC
