### ISSUE TITLE
v4 - the login page when used on a mobile device is a little unweildy!

### ISSUE THREAD

**Issue by Sc0th** [Ombi-app/Ombi#4114] opened 2021-03-27 10:41 UTC
**Describe the bug**

Login panel does not scale on mobile UI

**To Reproduce**

Use mobile to access ombi (as I imagine the majority of requester's will)

**Expected behavior**
Usable from mobile browser

**Screenshots**
no need :)

**Logs (Logs directory where Ombi is located)**
No logs

**Desktop (please complete the following information):**
 - IOS

**Ombi Version (please complete the following information):**
 - 4.0.1275.0 
- Plex
- MySQL

**Additional context**

**Comment by tidusjar** [comment] 2021-03-28 13:14
Scales fine on my Note 10+

can you get a screenshot?

**Comment by ctml91** [comment] 2021-04-03 02:41
Same with landing page.

Huawei P20 Pro, when menu is open there isnt much room to click to close it (the thin right bar). It should auto close once you select a new tab.

![Screenshot_20210402_223456](https://user-images.githubusercontent.com/74685281/113465742-8eb5ef00-9404-11eb-8873-c50e9648a101.jpg)

**Comment by Sc0th** [comment] 2021-04-03 06:21
![2021-03-28_21-28-39](https://user-images.githubusercontent.com/18287757/113470385-b26e4900-9487-11eb-82ff-44d46abb19ec.PNG)

Sorry forgot to get back to you! This is what it looks like on iphone XS max (chrome & firefox) also unable to resize.

**Comment by tidusjar** [comment] 2021-04-03 09:05
Duplicate of #4095

**Closed by tidusjar** 2021-04-03 09:05 UTC
