### ISSUE TITLE
cannot login into Ombi using Plex account

### ISSUE THREAD

**Issue by abendel** [Ombi-app/Ombi#4232] opened 2021-06-22 01:46 UTC
**Describe the bug**
Whenever I/Users try to login into Ombi (on a web page, works fine on computer/ IOS app) using plex authentication it says "you have successfully signed in. You may now close the window. The window, doesn't auto close and it doesn't log into ombi.
**To Reproduce**
1. "sign in with Plex"
2. Sign in
3. Wait for autoclose, which doesnt.
4. "cannot log you in"

**Expected behavior**
The Plex window auto closes and logs me in
**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Ombi Version (please complete the following information):**
 - Version 4.0.1425   
- Media Server Plex
- Database Type: SQLite (Please change if using MySQL)

**Additional context**
Love Ombi, but please help|!

**Comment by tidusjar** [comment] 2021-06-22 06:05
On the user management page, with the user guy are trying to login, does it state the user is a Plex user or local user?

**Comment by abendel** [comment] 2021-06-22 12:04
Yes, plex user

**Comment by pyarmak** [comment] 2021-06-24 20:52
My plex oauth also broke after updating to V4. I tried a clean config (using docker) and even in the wizard, the oauth login with plex does not work while the request token button worked great. Seems to be an issue with oauth.

**Comment by dpiper01** [comment] 2021-06-25 13:16
Same exact issue here, tried on mobile and PC with the same results. Thought it may have been a cache issue so followed [this commenters](https://www.reddit.com/r/Ombi/comments/g3rixm/ombi_login_loop_via_plex_sso/fnt24ch/?utm_source=share&utm_medium=ios_app&utm_name=iossmf&context=3) advice but it did not resolve the issue.

**Comment by tidusjar** [comment] 2021-06-25 14:21
So when the Plex OAuth window pops up and it states "You can now close this window" are you closing it?

Because Ombi will trigger once that window is closed

**Comment by pyarmak** [comment] 2021-06-25 14:42
> 
> 
> So when the Plex OAuth window pops up and it states "You can now close this window" are you closing it?
> 
> Because Ombi will trigger once that window is closed

Yes, window closes, button does a spinner, notification pops up saying auth failed.

**Comment by tidusjar** [comment] 2021-06-25 15:01
Can you open the dev tools? F12.

If so can you press the network tab and then refresh the page and attempt to log in.

You should see a call to `/api/v1/token/YOURPIN`, what is the response on that call?

**Comment by pyarmak** [comment] 2021-06-25 15:16
No problem, it posts some data (let me know if you want that as well) and the response is:
```
{
   "url":"https://app.plex.tv/auth#?code=REMOVED&context[device][product]=PashaFlix Requests&context[device][environment]=bundled&context[device][layout]=desktop&context[device][platform]=Web&context[device][device]=Ombi&clientID=REMOVED",
   "pinId":MYPIN
}
```

**Comment by tidusjar** [comment] 2021-06-25 15:18
There should be another call once you close the window a GET

**Comment by pyarmak** [comment] 2021-06-25 15:22
My apologies, here is the response to the GET request:
`{"errorMessage":"Could not authenticate with Plex"}`
Not very descriptive, unfortunately.

**Comment by tidusjar** [comment] 2021-06-25 15:51
Would discord be fine?

Out of curiosity what timezone is your ombi server in? Also is the time correctly set?

**Comment by pyarmak** [comment] 2021-06-25 16:03
Discord works for me (Nooblazor#7778).
As for your question, I use linuxserver/ombi docker container and set ENV TZ America/Winnipeg (my timezone). I'm not sure where to check the timezone in Ombi's UI.

**Comment by tidusjar** [comment] 2021-06-25 20:43
@pyarmak That was my theory, so nice investigation there.

Can you grab a new PIN Id and call `GET https://plex.tv/api/v2/pins/PINID` and does it contain the correct `expiresAt` and also the `authToken` property?

Because the only time we would get that message is if Ombi things the Pin has expired OR the authToken returned from the above API call is null/empty

**Comment by shawnbarton** [comment] 2021-06-26 06:55
I have also been experiencing this issue for a few days now with the latest docker container (which reports as 
4.0.1430 in the UI). Different users are affected on a rotating basis. A container restart temporarily resolves the issue - at least for the single reporting user. The logs don't seem to show any entries related to this.

I have some entries for this error but I'm unsure if it's related to the issue:
```
2021-06-25 04:19:26.841 +02:00 [Error] Something bad happened, ErrorMiddleware caught this
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.Data.Sqlite.SqliteConnectionExtensions.ExecuteNonQuery(SqliteConnection connection, String commandText, SqliteParameter[] parameters)
   at Microsoft.Data.Sqlite.SqliteTransaction.Commit()
   at System.Data.Common.DbTransaction.CommitAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalTransaction.CommitAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTransaction.CommitAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Ombi.Store.Repository.BaseRepository`2.InternalSaveChanges()
   at Ombi.Store.Repository.BaseRepository`2.Add(T content)
   at Ombi.Core.Engine.TvRequestEngine.AddRequest(TvRequests model, String requestOnBehalf)
   at Ombi.Core.Engine.TvRequestEngine.RequestTvShow(TvRequestViewModelV2 tv)
   at Ombi.Controllers.V2.RequestsController.RequestTv(TvRequestViewModelV2 tv)
   at lambda_method52196(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context)
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context)
```

And indeed when watching the developer tools during the login process, eventually, the `GET https://url/ombi/api/v1/token/xxxxx` returns with `error: "SQLite Error 5: 'database is locked'."`.

**Comment by tidusjar** [comment] 2021-06-26 09:53
That's a different issue, I'd suggest you change the database to use MySql, check the docs on how to do this

**Comment by shawnbarton** [comment] 2021-06-26 11:25
This is a new issue for me that is suddenly occurring in an otherwise long-running installation but I'll take your advice and switch this. Thanks!

**Comment by tidusjar** [comment] 2021-06-28 22:29
I've made some changes relating to this issue in the develop branch, more information is now outputted to the logs when there's a OAuth Pin failure, it would be amazing if someone could try the new build and let me know the results.

Also when you close the Plex OAuth window, how long does it take until Ombi tells you that it could not log in? Under or over 10 seconds?

**Comment by pyarmak** [comment] 2021-06-29 13:15
I can confirm that, at least on my end, the update you pushed seemed to have fixed the issue! 
I can login with plex oauth without issue on my setup now XD

**Comment by stevenpall** [comment] 2021-06-29 23:18
Also seems to have fixed the issue for me. Thanks!

**Comment by tidusjar** [comment] 2021-06-30 06:24
Awesome, so the issue was basically I was checking if the token had expired. The token issues is in local time, but I was checking against UTC

**Closed** 2021-06-30 06:24 UTC
