### ISSUE TITLE
Email messages do not work in 4.43.14

### ISSUE THREAD

**Issue by octomobiki** [Ombi-app/Ombi#5091] opened 2024-03-10 18:47 UTC
### Summary

I upgraded from 4.43.5 on March 8th and pulled the latest version, 4.43.14 from github. From there I shutdown the old version, copied the 3 DB files over to the new installation, and started it up. A few days later, I noticed that I was not getting emails when people were requesting shows.

When looking at the directory structure of the installation there was no such folder /bin under ombi.

### Ombi Version

4.43.14

### What platform(s) does this occur on?

Windows

### What database are you using?

SQLite (Default)

### Relevant log output

```shell
2024-03-10 10:42:27.816 -04:00 [ERR] Exception when attempting to send an email
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\username\ombi\bin\Debug\net6.0\Templates\BasicTemplate.html'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at Ombi.Notifications.Templates.EmailBasicTemplate.LoadTemplate(String subject, String body, String imgsrc, String logo, String url) in /home/runner/work/Ombi/Ombi/src/Ombi.Notifications.Templates/EmailBasicTemplate.cs:line 36
   at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi.Notifications/GenericEmailProvider.cs:line 40
```

**Comment by ExtremeFiretop** [comment] 2024-03-11 00:13
Duplicate of: https://github.com/Ombi-app/Ombi/issues/5088

**Comment by Thedaggert** [comment] 2024-04-03 20:48
It's working now in v4.43.16 so you can close it :-)

**Closed** 2024-04-04 17:04 UTC
