### ISSUE TITLE
User DB becomes corrupt - No one can log in.

### ISSUE THREAD

**Issue by K9Sports** [Ombi-app/Ombi#4247] opened 2021-07-05 05:52 UTC
**Describe the bug**
I install a clean Obmi on an Ubuntu Linux 20.04.2.  In about 24 hours after each install, the user DB or something becomes corrupt and I get a message that says "Incorrect username or password."  Not only can the Admin not log on, no locally created account nor Plex logins work.  I've tried deleting the DBs and restarting several times.  I've also tried clean installs (removing and deleting all files) of various versions.  The same thing happens.  Everything is working well and then a day or 2 later, it doesn't recogize accounts anymore.

**To Reproduce**
Doubt this can be easily recreated...
1.  Install Ombi
2.  Add users
3. Wait a day or two.
4. Try logging in.

**Expected behavior**
Allowing accounts to log in

**Screenshots**

![Screenshot 2021-07-05 123638](https://user-images.githubusercontent.com/86944819/124423406-47d2ef00-dd8f-11eb-8023-2ff703dee390.jpg)

**Logs (Logs directory where Ombi is located)**

[log-20210705.txt](https://github.com/Ombi-app/Ombi/files/6762019/log-20210705.txt)

**Desktop (please complete the following information):**
 - Ubuntu Linux 20.04.2

**Ombi Version (please complete the following information):**
 - Version v4.0.1430
- Media Server Plex
- Database Type: SQLite Or whatever is default on Ubuntu install

**Additional context**

**Comment by tidusjar** [comment] 2021-07-05 07:16
How are you adding these users? What type of users are they?

Are you using OAuth or manual login?

**Comment by K9Sports** [comment] 2021-07-05 10:57
> How are you adding these users? What type of users are they?
> 
> Are you using OAuth or manual login?

Both

**Comment by tidusjar** [comment] 2021-07-05 11:17
ok, that is very strange.

Can you please create a local user for myself, and then email me the Ombi.db to tidusjar@gmail.com with the credentials of that user and I can see if I can reproduce with your dataset to see what's going on

**Comment by K9Sports** [comment] 2021-07-05 11:56
Ok.  I'll have to get back to remove and reinstall.  You'll get the notice.  Thanks.

**Comment by K9Sports** [comment] 2021-07-06 00:16
> tidusjar@gmail.com

You're all set and login credentials have been sent.  Thanks!

**Comment by tidusjar** [comment] 2021-07-06 06:16
Thanks but I don't seem to have any emails 🤔

**Comment by K9Sports** [comment] 2021-07-06 09:25
> Thanks but I don't seem to have any emails 🤔
> 
> Actually I have one, ignore that, but what's my username?

Same as your email

**Comment by tidusjar** [comment] 2021-07-07 11:01
OK, i've been able to login successfully, i'm guessing it's been over 24 hours now?

**Comment by K9Sports** [comment] 2021-07-07 23:55
I haven't been able to log on since yesterday.

**Comment by tidusjar** [comment] 2021-07-08 06:25
Try using my user? Because I'm still able to

**Comment by K9Sports** [comment] 2021-07-08 11:25
> Try using my user? Because I'm still able to

Are you sure?  I tried your log in credentials too.  Get the same error.  I just tried it again before checking here.

**Comment by tidusjar** [comment] 2021-07-08 20:12
Interesting, can you please send me your Ombi.db file

**Comment by K9Sports** [comment] 2021-07-09 03:52
Sent.  Thanks!

**Comment by tidusjar** [comment] 2021-07-12 07:28
So the database you send me only contains one user. A `aq***58****0x@gmail.com`. That's why I cannot log in.

Something is possibly restoring the database from some sort of backup externally? Ombi does not have the ability to do restore any databases etc

**Comment by K9Sports** [comment] 2021-07-13 08:32
Well that's strange.  I have no idea who that email goes to.  And the db doesn't even have the admin account?  Really weird.  Is it being hacked somehow?

**Comment by tidusjar** [comment] 2021-07-13 13:38
The email i've purposely put in `*` to mask some of it.

That's the only account, so it's possible that something is deleting your Ombi.db and then ombi is restarting and the Wizard comes back so they can set it up, because that's what it looks like, a clean install.

Are you sure there's nothing removing the database files or if you are possibly using docker, are you not using the --storage parameter? https://docs.ombi.app/info/startup-parameters/#-storage

**Comment by K9Sports** [comment] 2021-07-13 23:39
The address you posted is nothing I put in.  Not mine nor yours so I don’t know what caused it.  It’s on a Ubuntu server so no Docker issue.  The db being replaced is the only explanation I know of but I have no clue how that’s being done.  I’m going to try a fresh install and use a different port in case it’s some sort of hacking.  None of the other Plex related applications has had this type of issue.

**Comment by tidusjar** [comment] 2021-07-14 08:47
My assumption is that the databases have been deleted and that your Ombi application is still open to the internet, if that's the case when someone goes to your ombi instance they would be presented with the Wizard and then they just went through it. Looking at the database you provided me that does indicate the case for that.

I don't believe this is some outside 'hack'

**Comment by K9Sports** [comment] 2021-07-14 10:17
Do the databases randomly delete itself?

**Comment by tidusjar** [comment] 2021-07-14 11:18
No, the database will never delete itself. Ombi Has no code to do that

**Comment by cmcooper1980** [comment] 2021-07-30 02:47
Has there been any update on this?  I am experiencing the same issue...I hardly use Ombi after setting it up for my users but when they reported they couldn't log in I was suprise by the GUI overhaul (I think it looks awesome) but my users can't reset their passwords nor can I as admin.  I am only able to get into Ombi because I have it integrated into Organizr and clicking Ombi link from there gets me right in.  This is Ombi on docker...installed via DockSTARTer so the install is all automated and yes, storage option is enabled.

**Comment by K9Sports** [comment] 2021-07-30 02:51
> Has there been any update on this? I am experiencing the same issue...I hardly use Ombi after setting it up for my users but when they reported they couldn't log in I was suprise by the GUI overhaul (I think it looks awesome) but my users can't reset their passwords nor can I as admin. I am only able to get into Ombi because I have it integrated into Organizr and clicking Ombi link from there gets me right in. This is Ombi on docker...installed via DockSTARTer so the install is all automated and yes, storage option is enabled.

Worked with tidusjar on this for awhile.  Couldn't find a solution or reason.  So even tho' Overseerr lacks a lot of features, I've switched over a week or so ago and haven't had a problem since.

**Comment by cmcooper1980** [comment] 2021-07-30 02:55
I just now created a local TestUser and I was able to log in...ALL my Emby Connect users cannot.  I will delete them all and re-add them...if Emby Connect doesn't work I will make them local user accounts (if that is a stable and viable workaround)

**Comment by K9Sports** [comment] 2021-07-30 02:59
> I just now created a local TestUser and I was able to log in...ALL my Emby Connect users cannot. I will delete them all and re-add them...if Emby Connect doesn't work I will make them local user accounts (if that is a stable and viable workaround)

We tried that.  It was just tidusjar and I as local users.  Still happened.  It seems that the database was replaced with another that had some user no one has heard of added.  Hope you have better luck.

**Comment by cmcooper1980** [comment] 2021-07-30 03:07
Maybe the update changed some user account mechanism because all my user types from before the major update were Emby Connect Users...  I had a total of 10 users or so.  So, I did what I said and deleted them all except my local account that works through Organizr...then through Ombi's settings I re-imported the Emby users....  I see now that the account types show as Emby User instead of Emby Connect Users...  I tried logging in as one of the users I know the password for and I got in!  Hopefully it is stable and not like your 24-48 hour issue...that would suck!

**Comment by psi5asp** [comment] 2021-07-30 05:35
For linux, you can get a list of last user logins using the `last` command. Check if there are any strange logins (external IP's etc. ) especially under root, or the user that owns the Ombi.db file. 

Also check the permissions of the /etc/Ombi folder and Ombi.db file, ensure they're only accessible by the Ombi service user (usually user = ombi, use `ps -aux | grep ombi` to see what user Ombi is running under)

You may also want to check the creation date (or last changed date) of the Omb.db file, using `stat -c %w /etc/Ombi/db` or even %x for last accessed, etc. (see `stat --help` for more info)

**Comment by designgears** [comment] 2021-08-03 22:50
> > Has there been any update on this? I am experiencing the same issue...I hardly use Ombi after setting it up for my users but when they reported they couldn't log in I was suprise by the GUI overhaul (I think it looks awesome) but my users can't reset their passwords nor can I as admin. I am only able to get into Ombi because I have it integrated into Organizr and clicking Ombi link from there gets me right in. This is Ombi on docker...installed via DockSTARTer so the install is all automated and yes, storage option is enabled.
> 
> Worked with tidusjar on this for awhile. Couldn't find a solution or reason. So even tho' Overseerr lacks a lot of features, I've switched over a week or so ago and haven't had a problem since.

Switched over as well, while it is missing a few features Ombi has, the features it does have work well.

**Comment by cmcooper1980** [comment] 2021-08-04 00:49
Just an update on my experience since it has been 5 days, I have not experience the 24-48 hour bug/issue @K9Sports has reported...  So for my situation I think I am good, was just a matter of the user types changing I guess...but for those that have a much larger user count, this would suck bad.

**Comment by tidusjar** [comment] 2021-08-10 11:25
Closing this due to currently not been able to find that this is an ombi issue. Regarding the User Type error, this is the reporting issue for that: https://github.com/Ombi-app/Ombi/issues/3751

**Closed by tidusjar** 2021-08-10 11:25 UTC
