### ISSUE TITLE
Emby’s externally facing hostname generates wrong URL

### ISSUE THREAD

**Issue by didusee** [Ombi-app/Ombi#3455] opened 2020-03-29 17:40 UTC
**Describe the bug**
The URL generated by ombi to the related media on my server is generated wrongly. Clicking on the button "view in emby" links to a black site. 

**To Reproduce**
what i put in ombi (settings > Externally Facing Hostname)
https:/myserveraddress.com/emby

the URL ombi generates and links to when clicking on "view in emby"
https://myserveraddress.com/emby/web/index.html#!/item/item.html?id=467687

**Expected behavior**
what the url is supposed to really look like in emby:
https://myserveraddress.com/emby/web/index.html#!/item?id=467687

**Desktop
 - OS: Docker on unraid 6.8.2
OS Architecture | X64, OS Description | Linux 4.19.98-Unraid #1 SMP Sun Feb 2 22:45:43 GMT 2020, Process Architecture | X64

**Ombi Version
 - Ombi 3.0.4892, 
 - Emby 4.4.0.40

**Additional context**
I already deleted the OmbiExternal.db, which makes no difference at all and does not fix the problem.
There is a preview f the URL, ombi will generate under the formfield "Externally Facing Hostname".
This on is already messed up and shows the following that would not work either: 
Current URL: "https://myserveraddress.com/emby/#!/item/item.html?id=1"

**Comment by Pyro2677** [comment] 2020-03-30 12:40
Yes I am also having this issue.

**Comment by didusee** [comment] 2020-03-30 13:40
I added a code change that might fix the problem to my understanding and would generate a valid URL to emby’s media

**Comment by Pyro2677** [comment] 2020-03-30 14:06
I have no idea what adding commit does but I hope old mate sees it and can quickly fix it for us on V3.

**Comment by tidusjar** [comment] 2020-03-30 14:52
No that will not work, it will break for Jellyfin users. The problem is I am always changing this part of the code because the URL keeps changing :(

**Comment by Pyro2677** [comment] 2020-03-30 15:01
Is there a way we can Manuall add the Serverid? Or have it so the user adds which ever one they have emby users click a button and Jellyfin users click another?

**Comment by tidusjar** [comment] 2020-03-30 15:04
The server id is not the issue here?

**Comment by Pyro2677** [comment] 2020-03-30 15:10
If I add “&serverId=*********” it will take me to my server even with the current way it is. That’s why I suggested it. But if you take out the bit the other guy said it also works. So it would be too hard to have Emby and Jellyfin Seperate?

**Comment by Pyro2677** [comment] 2020-03-30 15:14
You’re doing a great job with Ombi and I can’t believe I didn’t find it sooner and I can’t wait for V4.

**Comment by didusee** [comment] 2020-03-31 12:48
The Server ID has no need for Emby Users. Here’s a test with results …

`123.456.0.10:port/web/index.html#!/item/item.html?id=467687&serverId=serverId=…
`
Result: black Screen

`https://myserveraddress.com/web/index.html#!/item/item.html?id=467687&serverId=serverId=…
`
Result: black Screen

`123.456.0.10:port/web/index.html#!/item?id=467687&serverId=…
`
Result: correct media shown

`https://myserveraddress.com/web/index.html#!/item?id=467687&serverId=…
`
Result: correct media shown

`123.456.0.10:port/web/index.html#!/item?id=467687
`
Result: correct media shown

`https://myserveraddress.com/web/index.html#!/item?id=467687
`
Result: correct media shown

**Comment by tidusjar** [comment] 2020-03-31 14:01
thanks @didusee i'll try and fix soon

**Comment by tidusjar** [comment] 2020-03-31 14:56
This has been fixed in v4

**Comment by didusee** [comment] 2020-03-31 18:46
Thank you very much! really looking forward to it and keep up the amazing work.
Highly appreciated! :)

**Comment by Pyro2677** [comment] 2020-04-01 22:44
> This has been fixed in v4

Is there a chance you can fix it in V3? I have tried to install V4 on my linux VM but it's not playing ball for some reason.

**Comment by pawndev** [comment] 2020-04-07 08:45
Hi @Pyro2677 
@tidusjar merged this fix in the develop branch (see #3477 )
I think we need to wait until the next release 🙂

**Comment by tidusjar** [comment] 2020-04-07 08:52
This might not fix it according to #3476

**Comment by twanariens** [comment] 2021-06-13 09:32
This should be fixed with the complete rebuild of Emby in Ombi V4

**Closed by twanariens** 2021-06-13 09:32 UTC
Labels: bug / issue
